services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro  # optional, for Docker integration
    env_file:
      - .env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.0.111:3000  # <-- replace with YOUR server's IP
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
