---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - Cockpit:
        icon: cockpit.png
        href: https://192.168.0.111:9090
        description: System management & web terminal

    - Portainer:
        icon: portainer.png
        href: https://192.168.0.111:9443
        description: Docker container management
        siteMonitor: https://192.168.0.111:9443

    - Pi-hole:
        icon: pi-hole.png
        href: http://192.168.0.111:8053/admin
        description: DNS / ad blocker
        widget:
          type: pihole
          url: http://192.168.0.111:8053
          version: 6   # use 5 if you're on Pi-hole v5
          key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.0.111:8096
        description: Movies & TV

    - Immich:
        icon: immich.png
        href: http://192.168.0.111:2283
        description: Photo & video backup
        siteMonitor: http://192.168.0.111:2283

- Productivity:
    - Nextcloud:
        icon: nextcloud.png
        href: http://192.168.0.111:8081
        description: File sync & cloud storage
        siteMonitor: http://192.168.0.111:8081

    - Vaultwarden:
        icon: vaultwarden.png
        href: https://homelab.tail5068b.ts.net
        description: Password manager
